<div class="site-content">
    <div class="project-head-simple">
        <div class="title">
            <h1>Contact</h1>
        </div>
    </div>
    <div class="article_content" align="center">

        <?php
        /* ERRORS DISPLAY */
        if (isset($this->params->errors))
        {
            ?><table class="table table-condensed"><?php
            foreach ($this->params->errors as $error)
            {
                ?>
                    <tr class="danger">
                        <td>
                            <?php echo $error; ?>
                        <td>
                    </tr>
                    <?php
                }
                ?>
            </table>
            <?php
        }

        /* INFO DISPLAY */

        if (isset($this->params->infos))
        {
            ?><table class="table table-condensed"><?php
            foreach ($this->params->infos as $error)
            {
                ?>
                    <tr class="success">
                        <td>
                            <?php echo $error; ?>
                        <td>
                    </tr>
                    <?php
                }
            }
            ?>
        </table>

        <form method="post" action="">
            <p>
                <input name="nom" type="text" placeholder="Votre nom et prénom" size="50" />
            </p>
            <p>
                <input name="tel" type="text" placeholder="Votre numéro de téléphone" size="50" />
            </p>
            <p>
                <input name="email" type="email" placeholder="Votre adresse e-mail" size="50" />
            </p>
            <p>
                <select name="projet">
                    <?php query_posts('post_type=projets&order=ASC&posts_per_page=-1&projets_category=projets-en-cours'); ?>
                    <option value="">Choisissez un projet</option>
                    <option value="">Ma question ne concerne aucun projet</option>
                    <?php while (have_posts()) : the_post(); ?>
                        <option value="<?php the_title(); ?>"><?php the_title(); ?></option>
                    <?php endwhile; ?>
                </select>
            </p>
            <p>
                <textarea placeholder="Votre message"name="message" rows="10" cols="50"></textarea>
            </p>
            <p>
                <input type="submit" value="Envoyer" />
            </p>
        </form>
    </div>
</div>